//! Auto-generated attribute equivalences from OMNI Excel sheet.

pub struct StaticEquivalence {
    pub internal_name: &'static str,
    pub numeric_value: f64,
    pub display_name: &'static str,
}

pub const EQUIVALENCES: &[StaticEquivalence] = &[
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 0.0_f64, display_name: "Preparation" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 1.0_f64, display_name: "Connect patient" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 2.0_f64, display_name: "Therapy" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 3.0_f64, display_name: "End of therapy" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 4.0_f64, display_name: "Temporary disconnect" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 5.0_f64, display_name: "Change kit" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 6.0_f64, display_name: "Change therapy" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 7.0_f64, display_name: "Change dilution" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 8.0_f64, display_name: "Change anticoag" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 0.0_f64, display_name: "Preparation start screen" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 1.0_f64, display_name: "Preparation history view" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 2.0_f64, display_name: "Preparation previous kit removal" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 3.0_f64, display_name: "Preparation previous kit removal stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 4.0_f64, display_name: "Preparation previous kit removal unloading" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 5.0_f64, display_name: "Preparation scan kit" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 6.0_f64, display_name: "Preparation select therapy" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 7.0_f64, display_name: "Preparation device test" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 8.0_f64, display_name: "Preparation device test finished" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 9.0_f64, display_name: "Preparation install kit" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 10.0_f64, display_name: "Preparation install kit stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 11.0_f64, display_name: "Preparation install kit loading" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 12.0_f64, display_name: "Preparation install kit unloading" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 13.0_f64, display_name: "Preparation install kit ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 14.0_f64, display_name: "Preparation install bags" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 15.0_f64, display_name: "Preparation install bags ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 16.0_f64, display_name: "Preparation priming" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 17.0_f64, display_name: "Preparation priming stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 18.0_f64, display_name: "Preparation priming blood side filling start" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 19.0_f64, display_name: "Preparation priming blood side art line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 20.0_f64, display_name: "Preparation priming blood side ven line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 21.0_f64, display_name: "Preparation priming blood side fpc level adjustment" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 22.0_f64, display_name: "Preparation priming blood side vpc level adjustment" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 23.0_f64, display_name: "Preparation priming blood side filled" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 24.0_f64, display_name: "Preparation priming fluid side filling start" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 25.0_f64, display_name: "Preparation priming fluid side dial line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 26.0_f64, display_name: "Preparation priming fluid side ef line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 27.0_f64, display_name: "Preparation priming fluid side su g pre line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 28.0_f64, display_name: "Preparation priming fluid side su g post line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 29.0_f64, display_name: "Preparation priming fluid side su p main line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 30.0_f64, display_name: "Preparation priming fluid side plasma line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 31.0_f64, display_name: "Preparation priming fluid side flushing line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 32.0_f64, display_name: "Preparation priming fluid side spc level adjustment" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 33.0_f64, display_name: "Preparation priming fluid side bypass line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 34.0_f64, display_name: "Preparation priming fluid side seq ef line filling" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 35.0_f64, display_name: "Preparation priming fluid side epc level adjustment" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 36.0_f64, display_name: "Preparation priming fluid side filled" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 37.0_f64, display_name: "Preparation priming dialyser degassing" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 38.0_f64, display_name: "Preparation priming required rinsing" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 39.0_f64, display_name: "Preparation priming final test" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 40.0_f64, display_name: "Preparation priming final rinsing" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 41.0_f64, display_name: "Preparation priming rinsing finished" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 42.0_f64, display_name: "Preparation priming ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 43.0_f64, display_name: "Preparation ready for therapy" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 44.0_f64, display_name: "Preparation optional rinsing" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 45.0_f64, display_name: "Preparation optional rinsing ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 46.0_f64, display_name: "Preparation recirculation" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 47.0_f64, display_name: "Preparation confirm" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 48.0_f64, display_name: "Preparation cancel" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 49.0_f64, display_name: "Preparation cancel stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 50.0_f64, display_name: "Preparation cancel unloading" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 51.0_f64, display_name: "Preparation leaving" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 52.0_f64, display_name: "Connect patient" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 53.0_f64, display_name: "Connect patient stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 54.0_f64, display_name: "Connect patient running ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 55.0_f64, display_name: "Connect patient running ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 56.0_f64, display_name: "Connect patient ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 57.0_f64, display_name: "Therapy main" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 58.0_f64, display_name: "Therapy blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 59.0_f64, display_name: "Therapy patient care blood circ ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 60.0_f64, display_name: "Therapy patient care blood circ ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 61.0_f64, display_name: "Therapy blood circ ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 62.0_f64, display_name: "Therapy blood circ ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 63.0_f64, display_name: "Therapy running ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 64.0_f64, display_name: "Therapy running ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 65.0_f64, display_name: "Therapy periodic test" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 66.0_f64, display_name: "End of therapy return blood" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 67.0_f64, display_name: "End of therapy return blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 68.0_f64, display_name: "End of therapy return blood running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 69.0_f64, display_name: "End of therapy return blood ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 70.0_f64, display_name: "End of therapy disconnect all" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 71.0_f64, display_name: "End of therapy disconnect all stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 72.0_f64, display_name: "End of therapy disconnect all unloading" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 73.0_f64, display_name: "End of therapy leaving" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 74.0_f64, display_name: "Temporary disconnect patient return blood" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 75.0_f64, display_name: "Temporary disconnect patient return blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 76.0_f64, display_name: "Temporary disconnect patient return blood running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 77.0_f64, display_name: "Temporary disconnect patient return blood ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 78.0_f64, display_name: "Temporary disconnect patient disconnect pat" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 79.0_f64, display_name: "Temporary disconnect patient recirculation" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 80.0_f64, display_name: "Temporary disconnect patient recirculation stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 81.0_f64, display_name: "Temporary disconnect patient recirculation running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 82.0_f64, display_name: "Temporary disconnect patient confirm" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 83.0_f64, display_name: "Temporary disconnect patient connect patient" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 84.0_f64, display_name: "Temporary disconnect patient connect patient stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 85.0_f64, display_name: "Temporary disconnect patient connect patient running ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 86.0_f64, display_name: "Temporary disconnect patient connect patient running ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 87.0_f64, display_name: "Temporary disconnect patient connect patient ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 88.0_f64, display_name: "Change therapy select therapy" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 89.0_f64, display_name: "Change therapy connect lines" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 90.0_f64, display_name: "Change therapy confirm" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 91.0_f64, display_name: "Change therapy blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 92.0_f64, display_name: "Change therapy blood circ ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 93.0_f64, display_name: "Change therapy blood circ ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 94.0_f64, display_name: "Change dilution select dilution" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 95.0_f64, display_name: "Change dilution connect lines" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 96.0_f64, display_name: "Change dilution confirm" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 97.0_f64, display_name: "Change dilution blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 98.0_f64, display_name: "Change dilution blood circ ac stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 99.0_f64, display_name: "Change dilution blood circ ac running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 100.0_f64, display_name: "Change kit return blood" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 101.0_f64, display_name: "Change kit return blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 102.0_f64, display_name: "Change kit return blood running" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 103.0_f64, display_name: "Change kit return blood ready" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 104.0_f64, display_name: "Change kit disconnect kit" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 105.0_f64, display_name: "Change kit disconnect kit stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 106.0_f64, display_name: "Change kit disconnect kit unloading" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 107.0_f64, display_name: "Change anticoag select anticoag" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 108.0_f64, display_name: "Change anticoag unload syringe" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 109.0_f64, display_name: "Change anticoag change bags" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 110.0_f64, display_name: "Change anticoag confirm" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 111.0_f64, display_name: "Change anticoag blood stop" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 112.0_f64, display_name: "Change anticoag blood circ ac stop" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 0.0_f64, display_name: "Preparation" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 1.0_f64, display_name: "Connect patient" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 2.0_f64, display_name: "Therapy" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 3.0_f64, display_name: "End of therapy" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 4.0_f64, display_name: "Temporary disconnect" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 5.0_f64, display_name: "Change kit" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 6.0_f64, display_name: "Change therapy" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 7.0_f64, display_name: "Change dilution" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 8.0_f64, display_name: "Change anticoag" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 0.0_f64, display_name: "Preparation start screen" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 1.0_f64, display_name: "Preparation history view" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 2.0_f64, display_name: "Preparation previous kit removal" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 3.0_f64, display_name: "Preparation previous kit removal stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 4.0_f64, display_name: "Preparation previous kit removal unloading" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 5.0_f64, display_name: "Preparation scan kit" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 6.0_f64, display_name: "Preparation select therapy" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 7.0_f64, display_name: "Preparation device test" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 8.0_f64, display_name: "Preparation device test finished" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 9.0_f64, display_name: "Preparation install kit" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 10.0_f64, display_name: "Preparation install kit stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 11.0_f64, display_name: "Preparation install kit loading" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 12.0_f64, display_name: "Preparation install kit unloading" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 13.0_f64, display_name: "Preparation install kit ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 14.0_f64, display_name: "Preparation install bags" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 15.0_f64, display_name: "Preparation install bags ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 16.0_f64, display_name: "Preparation priming" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 17.0_f64, display_name: "Preparation priming stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 18.0_f64, display_name: "Preparation priming blood side filling start" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 19.0_f64, display_name: "Preparation priming blood side art line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 20.0_f64, display_name: "Preparation priming blood side ven line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 21.0_f64, display_name: "Preparation priming blood side fpc level adjustment" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 22.0_f64, display_name: "Preparation priming blood side vpc level adjustment" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 23.0_f64, display_name: "Preparation priming blood side filled" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 24.0_f64, display_name: "Preparation priming fluid side filling start" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 25.0_f64, display_name: "Preparation priming fluid side dial line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 26.0_f64, display_name: "Preparation priming fluid side ef line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 27.0_f64, display_name: "Preparation priming fluid side su g pre line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 28.0_f64, display_name: "Preparation priming fluid side su g post line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 29.0_f64, display_name: "Preparation priming fluid side su p main line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 30.0_f64, display_name: "Preparation priming fluid side plasma line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 31.0_f64, display_name: "Preparation priming fluid side flushing line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 32.0_f64, display_name: "Preparation priming fluid side spc level adjustment" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 33.0_f64, display_name: "Preparation priming fluid side bypass line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 34.0_f64, display_name: "Preparation priming fluid side seq ef line filling" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 35.0_f64, display_name: "Preparation priming fluid side epc level adjustment" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 36.0_f64, display_name: "Preparation priming fluid side filled" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 37.0_f64, display_name: "Preparation priming dialyser degassing" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 38.0_f64, display_name: "Preparation priming required rinsing" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 39.0_f64, display_name: "Preparation priming final test" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 40.0_f64, display_name: "Preparation priming final rinsing" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 41.0_f64, display_name: "Preparation priming rinsing finished" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 42.0_f64, display_name: "Preparation priming ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 43.0_f64, display_name: "Preparation ready for therapy" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 44.0_f64, display_name: "Preparation optional rinsing" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 45.0_f64, display_name: "Preparation optional rinsing ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 46.0_f64, display_name: "Preparation recirculation" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 47.0_f64, display_name: "Preparation confirm" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 48.0_f64, display_name: "Preparation cancel" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 49.0_f64, display_name: "Preparation cancel stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 50.0_f64, display_name: "Preparation cancel unloading" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 51.0_f64, display_name: "Preparation leaving" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 52.0_f64, display_name: "Connect patient" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 53.0_f64, display_name: "Connect patient stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 54.0_f64, display_name: "Connect patient running ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 55.0_f64, display_name: "Connect patient running ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 56.0_f64, display_name: "Connect patient ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 57.0_f64, display_name: "Therapy main" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 58.0_f64, display_name: "Therapy blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 59.0_f64, display_name: "Therapy patient care blood circ ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 60.0_f64, display_name: "Therapy patient care blood circ ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 61.0_f64, display_name: "Therapy blood circ ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 62.0_f64, display_name: "Therapy blood circ ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 63.0_f64, display_name: "Therapy running ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 64.0_f64, display_name: "Therapy running ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 65.0_f64, display_name: "Therapy periodic test" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 66.0_f64, display_name: "End of therapy return blood" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 67.0_f64, display_name: "End of therapy return blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 68.0_f64, display_name: "End of therapy return blood running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 69.0_f64, display_name: "End of therapy return blood ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 70.0_f64, display_name: "End of therapy disconnect all" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 71.0_f64, display_name: "End of therapy disconnect all stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 72.0_f64, display_name: "End of therapy disconnect all unloading" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 73.0_f64, display_name: "End of therapy leaving" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 74.0_f64, display_name: "Temporary disconnect patient return blood" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 75.0_f64, display_name: "Temporary disconnect patient return blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 76.0_f64, display_name: "Temporary disconnect patient return blood running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 77.0_f64, display_name: "Temporary disconnect patient return blood ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 78.0_f64, display_name: "Temporary disconnect patient disconnect pat" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 79.0_f64, display_name: "Temporary disconnect patient recirculation" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 80.0_f64, display_name: "Temporary disconnect patient recirculation stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 81.0_f64, display_name: "Temporary disconnect patient recirculation running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 82.0_f64, display_name: "Temporary disconnect patient confirm" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 83.0_f64, display_name: "Temporary disconnect patient connect patient" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 84.0_f64, display_name: "Temporary disconnect patient connect patient stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 85.0_f64, display_name: "Temporary disconnect patient connect patient running ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 86.0_f64, display_name: "Temporary disconnect patient connect patient running ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 87.0_f64, display_name: "Temporary disconnect patient connect patient ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 88.0_f64, display_name: "Change therapy select therapy" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 89.0_f64, display_name: "Change therapy connect lines" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 90.0_f64, display_name: "Change therapy confirm" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 91.0_f64, display_name: "Change therapy blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 92.0_f64, display_name: "Change therapy blood circ ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 93.0_f64, display_name: "Change therapy blood circ ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 94.0_f64, display_name: "Change dilution select dilution" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 95.0_f64, display_name: "Change dilution connect lines" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 96.0_f64, display_name: "Change dilution confirm" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 97.0_f64, display_name: "Change dilution blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 98.0_f64, display_name: "Change dilution blood circ ac stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 99.0_f64, display_name: "Change dilution blood circ ac running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 100.0_f64, display_name: "Change kit return blood" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 101.0_f64, display_name: "Change kit return blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 102.0_f64, display_name: "Change kit return blood running" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 103.0_f64, display_name: "Change kit return blood ready" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 104.0_f64, display_name: "Change kit disconnect kit" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 105.0_f64, display_name: "Change kit disconnect kit stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 106.0_f64, display_name: "Change kit disconnect kit unloading" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 107.0_f64, display_name: "Change anticoag select anticoag" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 108.0_f64, display_name: "Change anticoag unload syringe" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 109.0_f64, display_name: "Change anticoag change bags" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 110.0_f64, display_name: "Change anticoag confirm" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 111.0_f64, display_name: "Change anticoag blood stop" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 112.0_f64, display_name: "Change anticoag blood circ ac stop" },
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 0.0_f64, display_name: "Not selected" },
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 2.0_f64, display_name: "Citrate calcium" },
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 3.0_f64, display_name: "Heparint" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 0.0_f64, display_name: "Not selected" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 1.0_f64, display_name: "Post" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 2.0_f64, display_name: "Pre post" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 3.0_f64, display_name: "Pre" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 4.0_f64, display_name: "Post post" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 0.0_f64, display_name: "No valid therapy selected" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 1.0_f64, display_name: "Slow Continuous Ultrafiltration" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 2.0_f64, display_name: "Continuous Veno-Venous Hemofiltration" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 3.0_f64, display_name: "Continuous Veno-Venous Hemodialysis" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 4.0_f64, display_name: "Continuous Veno-Venous Hemodiafiltration" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 5.0_f64, display_name: "Hemoperfusion" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 6.0_f64, display_name: "Therapeutic Plasma Exchange" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 7.0_f64, display_name: "Cascade Filtration" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 8.0_f64, display_name: "Plasma adsorption/perfusion" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 9.0_f64, display_name: "Low Blood Volume Slow Continuous Ultrafiltration" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 10.0_f64, display_name: "Low Blood Volume Continuous Veno-Venous Hemofiltration" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 11.0_f64, display_name: "Low Blood Volume Continuous Veno-Venous Hemodialysis" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 12.0_f64, display_name: "Low Blood Volume Continuous Veno-Venous Hemodiafiltration" },
];
