//! Auto-generated attribute equivalences from OMNI Excel sheet.

pub struct StaticEquivalence {
    pub internal_name: &'static str,
    pub numeric_value: f64,
    pub display_name: &'static str,
}

pub const EQUIVALENCES: &[StaticEquivalence] = &[
    // ── c_trmt_main_state ──
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 0.0_f64, display_name: "Preparación" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 1.0_f64, display_name: "Conectar paciente" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 2.0_f64, display_name: "Terapia" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 3.0_f64, display_name: "Fin de terapia" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 4.0_f64, display_name: "Desconexión temporal" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 5.0_f64, display_name: "Cambiar kit" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 6.0_f64, display_name: "Cambiar terapia" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 7.0_f64, display_name: "Cambiar dilución" },
    StaticEquivalence { internal_name: "c_trmt_main_state", numeric_value: 8.0_f64, display_name: "Cambiar anticoagulante" },
    // ── c_trmt_sub_state: Preparation * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 0.0_f64, display_name: "Preparación pantalla inicio" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 1.0_f64, display_name: "Preparación vista historial" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 2.0_f64, display_name: "Preparación retirar kit anterior" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 3.0_f64, display_name: "Preparación retirar kit anterior detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 4.0_f64, display_name: "Preparación retirar kit anterior descargando" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 5.0_f64, display_name: "Preparación escanear kit" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 6.0_f64, display_name: "Preparación seleccionar terapia" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 7.0_f64, display_name: "Preparación prueba de dispositivo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 8.0_f64, display_name: "Preparación prueba de dispositivo finalizada" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 9.0_f64, display_name: "Preparación instalar kit" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 10.0_f64, display_name: "Preparación instalar kit detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 11.0_f64, display_name: "Preparación instalar kit cargando" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 12.0_f64, display_name: "Preparación instalar kit descargando" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 13.0_f64, display_name: "Preparación instalar kit listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 14.0_f64, display_name: "Preparación instalar bolsas" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 15.0_f64, display_name: "Preparación instalar bolsas listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 16.0_f64, display_name: "Preparación cebado" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 17.0_f64, display_name: "Preparación cebado detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 18.0_f64, display_name: "Preparación cebado inicio llenado lado sangre" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 19.0_f64, display_name: "Preparación cebado llenado línea arterial" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 20.0_f64, display_name: "Preparación cebado llenado línea venosa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 21.0_f64, display_name: "Preparación cebado ajuste nivel fpc lado sangre" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 22.0_f64, display_name: "Preparación cebado ajuste nivel vpc lado sangre" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 23.0_f64, display_name: "Preparación cebado lado sangre lleno" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 24.0_f64, display_name: "Preparación cebado inicio llenado lado fluido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 25.0_f64, display_name: "Preparación cebado llenado línea de diálisis" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 26.0_f64, display_name: "Preparación cebado llenado línea ef" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 27.0_f64, display_name: "Preparación cebado llenado línea su g pre" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 28.0_f64, display_name: "Preparación cebado llenado línea su g post" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 29.0_f64, display_name: "Preparación cebado llenado línea su p principal" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 30.0_f64, display_name: "Preparación cebado llenado línea plasma" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 31.0_f64, display_name: "Preparación cebado llenado línea de lavado" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 32.0_f64, display_name: "Preparación cebado ajuste nivel spc lado fluido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 33.0_f64, display_name: "Preparación cebado llenado línea bypass" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 34.0_f64, display_name: "Preparación cebado llenado línea seq ef" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 35.0_f64, display_name: "Preparación cebado ajuste nivel epc lado fluido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 36.0_f64, display_name: "Preparación cebado lado fluido lleno" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 37.0_f64, display_name: "Preparación cebado desgasificado de dializador" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 38.0_f64, display_name: "Preparación cebado enjuague requerido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 39.0_f64, display_name: "Preparación cebado prueba final" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 40.0_f64, display_name: "Preparación cebado enjuague final" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 41.0_f64, display_name: "Preparación cebado enjuague finalizado" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 42.0_f64, display_name: "Preparación cebado listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 43.0_f64, display_name: "Preparación listo para terapia" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 44.0_f64, display_name: "Preparación enjuague opcional" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 45.0_f64, display_name: "Preparación enjuague opcional listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 46.0_f64, display_name: "Preparación recirculación" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 47.0_f64, display_name: "Preparación confirmar" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 48.0_f64, display_name: "Preparación cancelar" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 49.0_f64, display_name: "Preparación cancelar detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 50.0_f64, display_name: "Preparación cancelar descargando" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 51.0_f64, display_name: "Preparación saliendo" },
    // ── c_trmt_sub_state: Connect patient * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 52.0_f64, display_name: "Conectar paciente" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 53.0_f64, display_name: "Conectar paciente detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 54.0_f64, display_name: "Conectar paciente circulación ac detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 55.0_f64, display_name: "Conectar paciente circulación ac activa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 56.0_f64, display_name: "Conectar paciente listo" },
    // ── c_trmt_sub_state: Therapy * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 57.0_f64, display_name: "Terapia principal" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 58.0_f64, display_name: "Terapia flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 59.0_f64, display_name: "Terapia cuidado paciente circulación ac detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 60.0_f64, display_name: "Terapia cuidado paciente circulación ac activa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 61.0_f64, display_name: "Terapia circulación ac detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 62.0_f64, display_name: "Terapia circulación ac activa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 63.0_f64, display_name: "Terapia funcionando ac detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 64.0_f64, display_name: "Terapia funcionando ac activo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 65.0_f64, display_name: "Terapia prueba periódica" },
    // ── c_trmt_sub_state: End of therapy * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 66.0_f64, display_name: "Fin de terapia retorno sanguíneo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 67.0_f64, display_name: "Fin de terapia retorno sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 68.0_f64, display_name: "Fin de terapia retorno sanguíneo activo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 69.0_f64, display_name: "Fin de terapia retorno sanguíneo listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 70.0_f64, display_name: "Fin de terapia desconectar todo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 71.0_f64, display_name: "Fin de terapia desconectar todo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 72.0_f64, display_name: "Fin de terapia desconectar todo descargando" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 73.0_f64, display_name: "Fin de terapia saliendo" },
    // ── c_trmt_sub_state: Temporarily disconnect * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 74.0_f64, display_name: "Desconexión temporal retorno sanguíneo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 75.0_f64, display_name: "Desconexión temporal retorno sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 76.0_f64, display_name: "Desconexión temporal retorno sanguíneo activo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 77.0_f64, display_name: "Desconexión temporal retorno sanguíneo listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 78.0_f64, display_name: "Desconexión temporal desconectar paciente" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 79.0_f64, display_name: "Desconexión temporal recirculación" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 80.0_f64, display_name: "Desconexión temporal recirculación detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 81.0_f64, display_name: "Desconexión temporal recirculación activa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 82.0_f64, display_name: "Desconexión temporal confirmar" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 83.0_f64, display_name: "Desconexión temporal conectar paciente" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 84.0_f64, display_name: "Desconexión temporal conectar paciente detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 85.0_f64, display_name: "Desconexión temporal conectar paciente circulación ac detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 86.0_f64, display_name: "Desconexión temporal conectar paciente circulación ac activa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 87.0_f64, display_name: "Desconexión temporal conectar paciente listo" },
    // ── c_trmt_sub_state: Change therapy * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 88.0_f64, display_name: "Cambiar terapia seleccionar terapia" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 89.0_f64, display_name: "Cambiar terapia conectar líneas" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 90.0_f64, display_name: "Cambiar terapia confirmar" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 91.0_f64, display_name: "Cambiar terapia flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 92.0_f64, display_name: "Cambiar terapia circulación ac detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 93.0_f64, display_name: "Cambiar terapia circulación ac activa" },
    // ── c_trmt_sub_state: Change dilution * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 94.0_f64, display_name: "Cambiar dilución seleccionar dilución" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 95.0_f64, display_name: "Cambiar dilución conectar líneas" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 96.0_f64, display_name: "Cambiar dilución confirmar" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 97.0_f64, display_name: "Cambiar dilución flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 98.0_f64, display_name: "Cambiar dilución circulación ac detenida" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 99.0_f64, display_name: "Cambiar dilución circulación ac activa" },
    // ── c_trmt_sub_state: Change kit * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 100.0_f64, display_name: "Cambiar kit retorno sanguíneo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 101.0_f64, display_name: "Cambiar kit retorno sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 102.0_f64, display_name: "Cambiar kit retorno sanguíneo activo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 103.0_f64, display_name: "Cambiar kit retorno sanguíneo listo" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 104.0_f64, display_name: "Cambiar kit desconectar kit" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 105.0_f64, display_name: "Cambiar kit desconectar kit detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 106.0_f64, display_name: "Cambiar kit desconectar kit descargando" },
    // ── c_trmt_sub_state: Change anticoag * ──
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 107.0_f64, display_name: "Cambiar anticoagulante seleccionar anticoagulante" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 108.0_f64, display_name: "Cambiar anticoagulante descargar jeringa" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 109.0_f64, display_name: "Cambiar anticoagulante cambiar bolsas" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 110.0_f64, display_name: "Cambiar anticoagulante confirmar" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 111.0_f64, display_name: "Cambiar anticoagulante flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "c_trmt_sub_state", numeric_value: 112.0_f64, display_name: "Cambiar anticoagulante circulación ac detenida" },
    // ── g_trmt_main_state_set ──
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 0.0_f64, display_name: "Preparación" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 1.0_f64, display_name: "Conectar paciente" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 2.0_f64, display_name: "Terapia" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 3.0_f64, display_name: "Fin de terapia" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 4.0_f64, display_name: "Desconexión temporal" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 5.0_f64, display_name: "Cambiar kit" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 6.0_f64, display_name: "Cambiar terapia" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 7.0_f64, display_name: "Cambiar dilución" },
    StaticEquivalence { internal_name: "g_trmt_main_state_set", numeric_value: 8.0_f64, display_name: "Cambiar anticoagulante" },
    // ── g_trmt_sub_state_set: Preparation * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 0.0_f64, display_name: "Preparación pantalla inicio" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 1.0_f64, display_name: "Preparación vista historial" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 2.0_f64, display_name: "Preparación retirar kit anterior" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 3.0_f64, display_name: "Preparación retirar kit anterior detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 4.0_f64, display_name: "Preparación retirar kit anterior descargando" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 5.0_f64, display_name: "Preparación escanear kit" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 6.0_f64, display_name: "Preparación seleccionar terapia" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 7.0_f64, display_name: "Preparación prueba de dispositivo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 8.0_f64, display_name: "Preparación prueba de dispositivo finalizada" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 9.0_f64, display_name: "Preparación instalar kit" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 10.0_f64, display_name: "Preparación instalar kit detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 11.0_f64, display_name: "Preparación instalar kit cargando" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 12.0_f64, display_name: "Preparación instalar kit descargando" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 13.0_f64, display_name: "Preparación instalar kit listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 14.0_f64, display_name: "Preparación instalar bolsas" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 15.0_f64, display_name: "Preparación instalar bolsas listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 16.0_f64, display_name: "Preparación cebado" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 17.0_f64, display_name: "Preparación cebado detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 18.0_f64, display_name: "Preparación cebado inicio llenado lado sangre" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 19.0_f64, display_name: "Preparación cebado llenado línea arterial" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 20.0_f64, display_name: "Preparación cebado llenado línea venosa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 21.0_f64, display_name: "Preparación cebado ajuste nivel fpc lado sangre" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 22.0_f64, display_name: "Preparación cebado ajuste nivel vpc lado sangre" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 23.0_f64, display_name: "Preparación cebado lado sangre lleno" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 24.0_f64, display_name: "Preparación cebado inicio llenado lado fluido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 25.0_f64, display_name: "Preparación cebado llenado línea de diálisis" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 26.0_f64, display_name: "Preparación cebado llenado línea ef" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 27.0_f64, display_name: "Preparación cebado llenado línea su g pre" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 28.0_f64, display_name: "Preparación cebado llenado línea su g post" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 29.0_f64, display_name: "Preparación cebado llenado línea su p principal" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 30.0_f64, display_name: "Preparación cebado llenado línea plasma" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 31.0_f64, display_name: "Preparación cebado llenado línea de lavado" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 32.0_f64, display_name: "Preparación cebado ajuste nivel spc lado fluido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 33.0_f64, display_name: "Preparación cebado llenado línea bypass" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 34.0_f64, display_name: "Preparación cebado llenado línea seq ef" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 35.0_f64, display_name: "Preparación cebado ajuste nivel epc lado fluido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 36.0_f64, display_name: "Preparación cebado lado fluido lleno" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 37.0_f64, display_name: "Preparación cebado desgasificado de dializador" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 38.0_f64, display_name: "Preparación cebado enjuague requerido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 39.0_f64, display_name: "Preparación cebado prueba final" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 40.0_f64, display_name: "Preparación cebado enjuague final" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 41.0_f64, display_name: "Preparación cebado enjuague finalizado" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 42.0_f64, display_name: "Preparación cebado listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 43.0_f64, display_name: "Preparación listo para terapia" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 44.0_f64, display_name: "Preparación enjuague opcional" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 45.0_f64, display_name: "Preparación enjuague opcional listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 46.0_f64, display_name: "Preparación recirculación" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 47.0_f64, display_name: "Preparación confirmar" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 48.0_f64, display_name: "Preparación cancelar" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 49.0_f64, display_name: "Preparación cancelar detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 50.0_f64, display_name: "Preparación cancelar descargando" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 51.0_f64, display_name: "Preparación saliendo" },
    // ── g_trmt_sub_state_set: Connect patient * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 52.0_f64, display_name: "Conectar paciente" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 53.0_f64, display_name: "Conectar paciente detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 54.0_f64, display_name: "Conectar paciente circulación ac detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 55.0_f64, display_name: "Conectar paciente circulación ac activa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 56.0_f64, display_name: "Conectar paciente listo" },
    // ── g_trmt_sub_state_set: Therapy * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 57.0_f64, display_name: "Terapia principal" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 58.0_f64, display_name: "Terapia flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 59.0_f64, display_name: "Terapia cuidado paciente circulación ac detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 60.0_f64, display_name: "Terapia cuidado paciente circulación ac activa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 61.0_f64, display_name: "Terapia circulación ac detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 62.0_f64, display_name: "Terapia circulación ac activa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 63.0_f64, display_name: "Terapia funcionando ac detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 64.0_f64, display_name: "Terapia funcionando ac activo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 65.0_f64, display_name: "Terapia prueba periódica" },
    // ── g_trmt_sub_state_set: End of therapy * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 66.0_f64, display_name: "Fin de terapia retorno sanguíneo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 67.0_f64, display_name: "Fin de terapia retorno sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 68.0_f64, display_name: "Fin de terapia retorno sanguíneo activo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 69.0_f64, display_name: "Fin de terapia retorno sanguíneo listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 70.0_f64, display_name: "Fin de terapia desconectar todo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 71.0_f64, display_name: "Fin de terapia desconectar todo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 72.0_f64, display_name: "Fin de terapia desconectar todo descargando" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 73.0_f64, display_name: "Fin de terapia saliendo" },
    // ── g_trmt_sub_state_set: Temporarily disconnect * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 74.0_f64, display_name: "Desconexión temporal retorno sanguíneo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 75.0_f64, display_name: "Desconexión temporal retorno sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 76.0_f64, display_name: "Desconexión temporal retorno sanguíneo activo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 77.0_f64, display_name: "Desconexión temporal retorno sanguíneo listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 78.0_f64, display_name: "Desconexión temporal desconectar paciente" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 79.0_f64, display_name: "Desconexión temporal recirculación" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 80.0_f64, display_name: "Desconexión temporal recirculación detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 81.0_f64, display_name: "Desconexión temporal recirculación activa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 82.0_f64, display_name: "Desconexión temporal confirmar" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 83.0_f64, display_name: "Desconexión temporal conectar paciente" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 84.0_f64, display_name: "Desconexión temporal conectar paciente detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 85.0_f64, display_name: "Desconexión temporal conectar paciente circulación ac detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 86.0_f64, display_name: "Desconexión temporal conectar paciente circulación ac activa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 87.0_f64, display_name: "Desconexión temporal conectar paciente listo" },
    // ── g_trmt_sub_state_set: Change therapy * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 88.0_f64, display_name: "Cambiar terapia seleccionar terapia" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 89.0_f64, display_name: "Cambiar terapia conectar líneas" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 90.0_f64, display_name: "Cambiar terapia confirmar" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 91.0_f64, display_name: "Cambiar terapia flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 92.0_f64, display_name: "Cambiar terapia circulación ac detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 93.0_f64, display_name: "Cambiar terapia circulación ac activa" },
    // ── g_trmt_sub_state_set: Change dilution * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 94.0_f64, display_name: "Cambiar dilución seleccionar dilución" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 95.0_f64, display_name: "Cambiar dilución conectar líneas" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 96.0_f64, display_name: "Cambiar dilución confirmar" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 97.0_f64, display_name: "Cambiar dilución flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 98.0_f64, display_name: "Cambiar dilución circulación ac detenida" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 99.0_f64, display_name: "Cambiar dilución circulación ac activa" },
    // ── g_trmt_sub_state_set: Change kit * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 100.0_f64, display_name: "Cambiar kit retorno sanguíneo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 101.0_f64, display_name: "Cambiar kit retorno sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 102.0_f64, display_name: "Cambiar kit retorno sanguíneo activo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 103.0_f64, display_name: "Cambiar kit retorno sanguíneo listo" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 104.0_f64, display_name: "Cambiar kit desconectar kit" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 105.0_f64, display_name: "Cambiar kit desconectar kit detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 106.0_f64, display_name: "Cambiar kit desconectar kit descargando" },
    // ── g_trmt_sub_state_set: Change anticoag * ──
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 107.0_f64, display_name: "Cambiar anticoagulante seleccionar anticoagulante" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 108.0_f64, display_name: "Cambiar anticoagulante descargar jeringa" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 109.0_f64, display_name: "Cambiar anticoagulante cambiar bolsas" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 110.0_f64, display_name: "Cambiar anticoagulante confirmar" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 111.0_f64, display_name: "Cambiar anticoagulante flujo sanguíneo detenido" },
    StaticEquivalence { internal_name: "g_trmt_sub_state_set", numeric_value: 112.0_f64, display_name: "Cambiar anticoagulante circulación ac detenida" },
    // ── g_anticoag_mode_set ──
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 0.0_f64, display_name: "No seleccionado" },
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 1.0_f64, display_name: "Ninguno" },
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 2.0_f64, display_name: "Citrato calcio" },
    StaticEquivalence { internal_name: "g_anticoag_mode_set", numeric_value: 3.0_f64, display_name: "Heparina" },
    // ── g_substitution_mode_set ──
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 0.0_f64, display_name: "No seleccionado" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 1.0_f64, display_name: "Post" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 2.0_f64, display_name: "Pre post" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 3.0_f64, display_name: "Pre" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 4.0_f64, display_name: "Post post" },
    StaticEquivalence { internal_name: "g_substitution_mode_set", numeric_value: 5.0_f64, display_name: "Ninguno" },
    // ── g_therapy_mode_set ──
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 0.0_f64, display_name: "Ninguna terapia válida seleccionada" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 1.0_f64, display_name: "Ultrafiltración Lenta Continua" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 2.0_f64, display_name: "Hemofiltración Veno-Venosa Continua" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 3.0_f64, display_name: "Hemodiálisis Veno-Venosa Continua" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 4.0_f64, display_name: "Hemodiafiltración Veno-Venosa Continua" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 5.0_f64, display_name: "Hemoperfusión" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 6.0_f64, display_name: "Intercambio Plasmático Terapéutico" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 7.0_f64, display_name: "Filtración en Cascada" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 8.0_f64, display_name: "Adsorción/Perfusión Plasmática" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 9.0_f64, display_name: "UFLC Bajo Volumen Sanguíneo" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 10.0_f64, display_name: "HDF-VVC Bajo Volumen Sanguíneo" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 11.0_f64, display_name: "HD-VVC Bajo Volumen Sanguíneo" },
    StaticEquivalence { internal_name: "g_therapy_mode_set", numeric_value: 12.0_f64, display_name: "HDF-VVC Bajo Volumen Sanguíneo" },
];
